### ISSUE TITLE
Crash using new installreferrer api

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-android-sdk#47]
We're getting this crash when using CleverTap 3.6.3 which uses the new install referrer api.

Note that we are explicitly using installreferrer version `1.0`, not `1.1`, because Google didn't properly release version `1.1`:

https://issuetracker.google.com/issues/145557612

Google released a 1.1 build which had a crash (in the above issue), then they re-released a new build with the same version 1.1 with a fix.

We cannot use this version 1.1 because the fact that there have been two different builds with different code, but the same version 1.1 means we can't have repeatable builds. We're waiting for a fix in a new version number of install referrer.

```
java.lang.NoSuchMethodError: No virtual method getGooglePlayInstantParam()Z in class Lcom/android/installreferrer/api/ReferrerDetails; or its super classes (declaration of 'com.android.installreferrer.api.ReferrerDetails' appears in /data/app/lifeisbetteron.com.test-E3ShMD11ilZ7-WvFFFkUig==/base.apk)
       at com.clevertap.android.sdk.CleverTapAPI$43.onInstallReferrerSetupFinished(CleverTapAPI.java:6379)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:222)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by calvarez-ov** [comment]
Actually, we also have the crash with installreferrer 1.1, it appears

**Comment by calvarez-ov** [comment]
Actually, we also have the crash with installreferrer 1.1, it appears

**Comment by darshanclevertap** [comment]
@calvarez-ov I went through the Google Issue and that is very lazy of them to do so. We use the dependency as `compileOnly`. We have internally tested with 1.1 as a gradle dependency in our app and it works. Could you clear gradle caches and rebuild and check? `getGooglePlayInstantParam` is a public API and it would be weird for it not to be there. 

Also, we do have the old way of install referrer via broadcast receiver still working as of now, you can use that as of now till Google comes up with a 1.2 version.

**Comment by calvarez-ov** [comment]
Could you please make CleverTap compatible with install referrer 1.0? Is this new api `getGooglePlayInstantParam` really necessary? Can using it wait until google fixes the install referrer library?

It's really important to have repeatable builds. And I'm not sure google will fix the library before the broadcast receiver mechanism stops working in March.

**Comment by darshanclevertap** [comment]
@calvarez-ov If you had pointed this out to us before we could have released for the 1.0 dependency. Since we have already released for v1.1, let me discuss this internally if releasing another CT SDK version is feasible for us.

**Comment by calvarez-ov** [comment]
> Actually, we also have the crash with installreferrer 1.1, it appears

> Could you clear gradle caches and rebuild and check?

Here's an update after testing again with different caches, doing clean builds with `--no-daemon --no-build-cache` to make sure we're not having anything stale when building:

* :x: installreferrer **1.0**: crash due to missing `getGooglePlayInstantParam()` (this github issue)
* :x: Installreferrer **1.1**, the **original** one (it's cached by a nexus mirror we have): `java.lang.ClassNotFoundException: Didn't find class "com.google.android.aidl.BaseStub" on path` (this is the issue opened with google)
* ✔️ installreferrer **1.1**, the **current** one: no crash

So indeed, if you were fortunate enough to not have pulled in installreferrer 1.1 when it was still buggy, it works.

If we wanted to make sure this would work for us, we'd have to make sure each developer clears their gradle cache, and also make sure our nexus mirror loses this old 1.1 version, and any other caches in our CI be cleared.

I think it would be best to avoid using this 1.1 version, as other developers of other apps may be running into this as well (I know some who have also rolled back to 1.0 for this reason).

Many thanks for your consideration!

**Comment by calvarez-ov** [comment]
Update: To not be blocked, we will try to clear all our caches and use the new 1.1 which doesn't crash.  But it may be useful still for other CleverTap customers to support 1.0.

**Comment by calvarez-ov** [comment]
Actually, we just discovered a new issue with the install referrer library 1.1 (and 1.1.1 which was published today).
This library adds additional permissions to the app using it:
`WRITE_EXTERNAL_STORAGE`
`READ_EXTERNAL_STORAGE`
`READ_PHONE_STATE`

More info here: https://issuetracker.google.com/issues/146115244

**Comment by darshanclevertap** [comment]
@calvarez-ov Sorry for the delay but we really do not have the bandwidth to downgrade to 1.0 for now. We will stay at 1.1 and keep an eye on the 1.1.1 issue and if Google fixes this before March, I will update it to the next lib version.

**Comment by darshanclevertap** [comment]
@calvarez-ov We decided to revert to v1.0. Please checkout the latest release v3.6.4. Thanks!

**Comment by rishabh876** [comment]
Google installreferrer 1.1.2 is now out with the fix for unnecessary permissions.
Does 3.7.0 version has this dependency or should we still keep using 1.0?

**Comment by darshanclevertap** [comment]
@rishabh876 You can use v1.1.2, it should not cause a conflict with the CleverTap Android SDK dependency of v1.0
