### ISSUE TITLE
Crash on Android 4.4 after updating SDK to v4.1.0

### ISSUE THREAD

**Issue by NikSatyr** [CleverTap/clevertap-android-sdk#168]
**Describe the bug**
The SDK crashes on init on Android 4.4 devices

**To Reproduce**
1. Try to init the SDK v4.1.0 on Android 4.4

**Expected behavior**
The SDK v.4.1.0 does not crash on Android 4.4

**Screenshots/Logs**
[crash-log.txt](https://github.com/CleverTap/clevertap-android-sdk/files/6377269/crash-log.txt)

**Environment (please complete the following information):**
 - Device: Nexus 5 Emulator
 - OS: Android 4.4
 - CleverTap SDK Version: 4.1.0
 - Android Studio Version: 4.1.3

**Additional context**
After investigating the crash, I discovered that the issue was present in SDK 4.0.4, but did not crash the app (it would just log a warning if you set a kinda secret logging level >2) and thus remained unnoticed:
[log-4.0.4.txt](https://github.com/CleverTap/clevertap-android-sdk/files/6377315/log-4.0.4.txt)

The problem in v.4.1.0 is com.clevertap.android.sdk.validation.ManifestValidator:59:
`validateServiceInManifest((Application) context.getApplicationContext(), CTBackgroundJobService.class.getName());`

Since JobService was added in Android 5.0 Lollipop, checking for this on 4.4 won't succeed as this class won't be present in the classpath. This results in NoClassDefFoundError that was somehow handled in SDK v4.0.4, but I can see there were some internal changes to that in v4.1.0

**Comment by piyush-kukadiya** [comment]
@NikSatyr We will try to reproduce and fix this in next release.

**Comment by william-ct** [comment]
Hi @NikSatyr , we have fixed the crash in the new version of the SDK(4.1.1).Let us know if you are facing any other issues.Cheers for reporting!

**Comment by NikSatyr** [comment]
@william-ct thanks, the issue seems to be resolved in 4.1.1.
